### PR TITLE
Always bundle the theme CSS/JS

### PR DESCRIPTION
**Pull request by davidfischer**
This removes the `{% if READTHEDOCS %}` conditionals around the theme JS/CSS. The goal here is to uncouple the code injected by readthedocs.org into this theme from the version of the CSS/JS on the theme itself.

This change will have a required change in the readthedocs.org repo which I will link when that PR is created. There is also an optional (but highly recommended) change coming in the [readthedocs-sphinx-ext](https://github.com/rtfd/readthedocs-sphinx-ext) repo which I will also link to.

### CODE REVIEW

**Comment by davidfischer** [comment]
Here's the corresponding .org PR: https://github.com/rtfd/readthedocs.org/pull/3968

Without merging that PR, the theme JS will be included twice. This doesn't seem to break anything.

There's also a PR on the readthedocs-sphinx-ext repo: https://github.com/rtfd/readthedocs-sphinx-ext/pull/39

Without that PR, the theme CSS will be included twice. This doesn't break anything. One thing to note is that the CSS from media.readthedocs.org is included later in the DOM so it will take precedence over the theme bundled CSS. We should just merge the above PR to fix that.

**Comment by davidfischer** [comment]
Coupled with the other PRs, this fixes #610.

**Comment by davidfischer** [comment]
Will do. I will also update the changelog to mention that 0.3.0 has some issues.

**Comment by ericholscher** [comment]
Maybe we can remove the other 2 `{% if READTHEDOCS %}` sections, and have that be 1.0 :)

**Comment by davidfischer** [comment]
> Maybe we can remove the other 2 {% if READTHEDOCS %} sections, and have that be 1.0 :)

Let's make that a goal for 1.0. However, I think targeting this for 0.4.0 would be good.

**Pull request merged**
