### PR TITLE
Swagger plugin

### PR DESCRIPTION
**Pull request by txomon**
Basically, the swagger ui requires not only the plugin but also files in the theme. Suggestions accepted!

### CODE REVIEW

**Comment by txomon** [comment]
You probably want to tweak something there... A quick preview just in case you are wondering what this looks like...

image

**Comment by ericholscher** [comment]
This looks really neat! It seems like this could live as an extension to Sphinx itself, instead of shipping with our theme. Is there a reason you're adding it to the theme instead of as a standalone extension?

**Comment by txomon** [comment]
Yeah, it requires resources in the theme and I have no idea on how to
provide them other way.

**Comment by Blendify** [comment]
I agree, I would much rather see something like this be added to sphinxcontrib what exactly is forcing you to only bundle this with the theme?

**Comment by txomon** [comment]
Hello, I don't understand the question. @Blendify How is this different question from the one I already answered?

If you check the PR, you will see that there are come css/js resources that need to be added to the theme for it to work.

**Comment by Blendify** [comment]
Is it not possible to make the css/js work in a sphinx extension?

**Comment by txomon** [comment]
The problem I have is that I haven't found a way to do that :/, I can specify how to render a node, but AFAIK I cannot inject references to resources... I haven't found any example similar to this one, as they all injected everything together, so no idea.

Also I understand there should be css work to adapt it to the rtd theme, but I have no knowledge on fronted.

**Comment by Blendify** [comment]
Please read the sphinx application docs (sphinx.app) which has some tools for injecting css and js script files

**Pull request closed without merging**
