### PR TITLE
Readme sections in sidebar

### LINKED ISSUE #523: README sections not in sidebar
Since #520, the README is part of the built documentation, but the headers in README do not appear in the sidebar at http://sphinx-rtd-theme.readthedocs.io/en/latest/index.html.

### PR DESCRIPTION
**Pull request by jessetan**
This PR makes the README sections appear in the navbar.
It uses an intermediate file to indirectly include the README (`toctree` does not allow including files that are in a parent directory).
The location of the README remains unchanged (so it renders nicely on GitHub).

A JavaScript redirect is used to send viewers directly to the README page, rather than displaying a page containing only the table of contents.

Fixes #523.

### CODE REVIEW

**Comment by Blendify** [comment]
Personally, I do not think the redirect is needed.

**Comment by jessetan** [comment]
@Blendify do you think the landing page needs some more content then? Without the redirect,  readers will land on a page with only toctree that they need to click through.

**Comment by Blendify** [comment]
We can include the first couple of lines from the readme me? Or just
manually duplicate the content.

**Comment by Blendify** [comment]
Poke, I would just include an introductory statement in the index this should be adequate to describe the project.

**Comment by jessetan** [comment]
I'm waiting to see what the outcome of #532 is, since it may affect the way we can get the README to show up in the sidebar.

**Comment by Blendify** [comment]
The is obsolete now with 67bb54d450a6cd0c7c8fb452c13af2a50bab9b21

**Pull request closed without merging**
