### PR TITLE
Docs refactor

### LINKED ISSUE #557: Refactor readme
We should refactor the readme and split it up into more files and move these to the docs folder. Then we can we just link to these pages. The readme should be more of an introduction.

### PR DESCRIPTION
**Pull request by Blendify**
Fix #557 see individual commits for details

### CODE REVIEW

**Comment by ericholscher** [comment]
I'd like to see more copy on the docs index page, not just a TOC. Also would be good to figure out how to stop the title from displaying in the sidebar (eg. http://sphinx-rtd-theme.readthedocs.io/en/docs-refactor/installing.html)

**Comment by ericholscher** [comment]
Big +1 on splitting up the content into multiple pages though. This makes a lot of sense, just needs a bit more cleanup on the landing page. I don't want to make people click GitHub -> RTD -> TOC to get any real info.

**Comment by Blendify** [comment]
@ericholscher 
> Also would be good to figure out how to stop the title from displaying in the sidebar (eg. http://sphinx-rtd-theme.readthedocs.io/en/docs-refactor/installing.html) 

What do you mean exactly about the title in the sidebar? Do you want all these docs under one collapsible heading? 

> This makes a lot of sense, just needs a bit more cleanup on the landing page. I don't want to make people click GitHub -> RTD -> TOC to get any real info.

What do you mean by real info? What about including the readme file before the toctree?

**Comment by ericholscher** [comment]
* Remove the "Read the Docs Sphinx Theme" , or the logo, from the sidebar. It looks weird with both.

* Including the readme above the TOC would be a good start. That way we only have that info in one place.

**Comment by Blendify** [comment]
Addressed the review points. It looks really good now. So glad I got around to this. BTW with the PR #535 becomes obsolete.

**Pull request merged**
