### PR TITLE
Fix line endings

### LINKED ISSUE #708: git shows unstaged files after clone
### Problem

My fresh install git shows unstaged files directly after cloning this repository.

#### Error Logs/Results

    `xxxx~/Workspaces/python$ git clone https://github.com/rtfd/sphinx_rtd_theme.git
    Cloning into 'sphinx_rtd_theme'...
    remote: Enumerating objects: 5, done.
    remote: Counting objects: 100% (5/5), done. 
    remote: Compressing objects: 100% (5/5), done.
    remote: Total 4566 (delta 0), reused 0 (delta 0), pack-reused 4561 
    Receiving objects: 100% (4566/4566), 10.42 MiB | 1.72 MiB/s, done. 
    Resolving deltas: 100% (2751/2751), done.
    xxxx:~/Workspaces/python$ cd sphinx_rtd_theme/ 
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ git status
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	    modified:   docs/make.bat

    no changes added to commit (use "git add" and/or "git commit -a")
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ git config -l
    core.repositoryformatversion=0
    core.filemode=true
    core.bare=false
    core.logallrefupdates=true
    remote.origin.url=https://github.com/rtfd/sphinx_rtd_theme.git
    remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
    branch.master.remote=origin
    branch.master.merge=refs/heads/master
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ 
    `

#### Expected Results

Why is there a unstaged file? Am i missing some configuration

### Environment Info

- git version 2.17.1

### PR DESCRIPTION
**Pull request by davidfischer**
Unfortunately this is very hard to test but I believe this change will fix the issues with CRLF in the .bat file. Another possibility is simply to remove the line `*       text eol=lf` in `.gitattributes`.

https://www.git-scm.com/docs/gitattributes
https://help.github.com/articles/dealing-with-line-endings/

Fixes #708.

### CODE REVIEW

**Comment by davidfischer** [comment]
I know I mentioned this is hard to test but I did test this after merging and it does appear to fix the problem.

**Comment by jessetan** [comment]
I sure hope this helps because I now have the original problem every time I switch branches that did not have this change yet. It should work itself out eventually, but maybe removing `* text eol=lf` (setting it to auto) would be preferable if it also solves the original issue.

**Comment by catrina4200** [comment]
> Unfortunately this is very hard to test but I believe this change will fix the issues with CRLF in the .bat file. Another possibility is simply to remove the line `* text eol=lf` in `.gitattributes`.
> 
> https://www.git-scm.com/docs/gitattributes
> https://help.github.com/articles/dealing-with-line-endings/
> 
> Fixes #708.

.gitattributes

**Comment by catrina4200** [comment]
davidfischer/fix-line-endings

**Pull request merged**
