### PR TITLE
Nicer styles for <kbd>

### LINKED ISSUE #669: Nicer styles for <kbd>
### Problem

Currently the `:kbd:` role, or more precisely the `<kbd>` HTML tag, renders like this:

image

I think it would be nicer if the styles were closer to what GitHub does, so one could document keys to press or buttons to click with more visual aid:

<kbd>Download</kbd>

### Reproducible Project

Link: https://cojeapi.readthedocs.io/cs/latest/content/02-klient-server.html#klient-v-terminalu-curl (the "Windows" tab)

```rst
Click on :kbd:`Download`.
```

#### Expected Results

The role renders like something resembling a button or a computer key.

### Environment Info

- Python Version: not relevant
- Sphinx Version: not relevant
- RTD Theme Version: 0.4.0

### PR DESCRIPTION
**Pull request by Blendify**
Fixes #669 

Style:
literal

### CODE REVIEW

**Comment by jessetan** [comment]
Font size looks good.

Two more suggestions (apart from the lighter bg):

Removing the margin makes it fit better within the line
margin

Adding some shadow can make it look more buttony (here `box-shadow: grey 0px 2px`)
screen shot 2018-10-22 at 20 34 43

**Comment by jessetan** [comment]
LGTM. Background color could be lighter to increase contrast for legibility, but no biggie.

**Comment by honzajavorek** [comment]
👍 Love it! Can we get it merged (and released)?

**Comment by Blendify** [comment]
Sure lets get another confirmation first.

**Comment by ericholscher** [comment]
👍

**Comment by loganlinn** [comment]
Did this ever make it into a release? It looks like the base branch for this PR is not fully merged into master: https://github.com/readthedocs/sphinx_rtd_theme/compare/fix-671

**Comment by Blendify** [comment]
@loganlinn it seems you are right not sure how that happened

**Comment by jobec** [comment]
Did you test this with ``:kbd:`ctrl+shift` `` ?
It seems to produce a box in a box like this:

image

Based on the generated html:
```html
Keyboard buttons: press <kbd class="kbd docutils literal notranslate"><kbd class="kbd docutils literal notranslate">ctrl</kbd>+<kbd class="kbd docutils literal notranslate">shift</kbd></kbd> <kbd class="kbd docutils literal notranslate">enter</kbd>
```

**Pull request merged**
