### PR TITLE
Caption rework

### PR DESCRIPTION
**Pull request by Blendify**
Before:
screenshot from 2017-03-07 12 59 34

After:

screenshot from 2017-03-07 12 58 45

fixes https://github.com/rtfd/sphinx_rtd_theme/issues/315

### CODE REVIEW

**Comment by Blendify** [comment]
Ok this is ready for review the before and after pictures are above except the after picture does not have the vertical-align change.

**Comment by Blendify** [comment]
> The decreased font size and decreased contrast reduce the readability of the captions. This is an negative change for accessability of our docs

This was done to better distinguish body text and captions.

> The table formatting appears to have regressed, I prefer the formatting before this change

I think I can still improve this. But mind being more specific here?

**Comment by agjohnson** [comment]
> This was done to better distinguish body text and captions.

The theme isn't currently displaying any other text at this low contrast, so this is a bit of a stylistic deviation on top of being a fairly unreadable. There might be some other treatment to the captions that preserves readability and still distinguishes the elements.

> I think I can still improve this. But mind being more specific here?

The table inner cell borders are dark in the after screengrab.

**Comment by Blendify** [comment]
This patch now also fixes #292

**Comment by Blendify** [comment]
Reopened as #401

**Pull request closed without merging**
