### PR TITLE
Prepare release 0.3.1

### PR DESCRIPTION
**Pull request by agjohnson**
This is a bugfix release that addresses some minor styling fixes and
compatibility with mkdocs and previous version theme layout.html.

### CODE REVIEW

**Comment by davidfischer** [comment]
👍

**Comment by mdeisrael** [comment]
100

**Comment by mdeisrael** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by mdeisrael** [comment]
[New Text Document.txt](https://github.com/rtfd/sphinx_rtd_theme/files/2363535/New.Text.Document.txt)

**Pull request merged**
