### PR TITLE
Replace the name 'Dave Snider' with RTD

### PR DESCRIPTION
**Pull request by Blendify**

### CODE REVIEW

**Comment by ericholscher** [comment]
I don't think we have a standard way of doing it, but probably should. I think "Read the Docs, Inc & contributors" is probably the most legally correct.

**Comment by ericholscher** [comment]
I do feel bad removing Dave's name from the explicit listing, since it was his creation originally. Is there a problem we're trying to solve with this?

**Comment by Blendify** [comment]
Not specifically just that we are not giving hardly any attribution to current authors. I would be fine with add Dave to "Read the Docs, Inc & contributors"

**Comment by davidfischer** [comment]
Are we agreed on "Dave Snider, Read the Docs, Inc. & contributors"?

**Comment by ericholscher** [comment]
"Dave Snider, Read the Docs, Inc. & contributors" sgtm.

**Pull request merged**
